# fly.toml app configuration file generated for fsocicd on 2023-07-22T13:13:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fsocicd"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
[http_check]
  interval = 10000  # Check interval in milliseconds (e.g., 10000ms = 10 seconds)
  timeout = 5000    # Check timeout in milliseconds (e.g., 5000ms = 5 seconds)
  method = "GET"    # HTTP method to use for the health check (GET, POST, etc.)
  path = "/"        # The path to check on the server
  protocol = "http" # The protocol to use (http or https)
  host = ""         # Optional: specify a custom host header
  [http_check.headers]