name: Render

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.7.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-xxxxxxxxxxxxxxxxxxxx
          retries: 20
          wait: 16000
          sleep: 30000