name: Testing stuff

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

# on:
#   push:
#     branches:
#       - feature-2

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Failing step
        id: demo
        run: echo "wew"
      - name: Notif Fail to Discord
        uses: rjstone/discord-webhook-notify@v1
        if: ${{failure() && github.event_name == 'push'}}
        with:
          severity: info
          description: commit
          details: '${{ github.event.head_commit.url}} by ${{ github.actor}} broke the build :('
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  job_2:
    needs: [a_test_job]
    runs-on: ubuntu-20.04
    steps:
      - name: check
        run: echo "sda"
      - name: Notif Success to Discord
        uses: rjstone/discord-webhook-notify@v1
        if: ${{success()}}
        with:
          severity: info
          description: ''
          details: 'to ${{github.event.repository.homepage}} by ${{ github.actor}}'
          text: A new version of Pokedex doployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
