# name: e2e tests
# on:
#   push:
#     branches:
#       - master
# jobs:
#   E2E_TESTS:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '16'
#       - name: npm install
#         run: npm install
#       - uses: cypress-io/github-action@v2
#         with:
#           browser: chrome
#           command: npm run test:e2e
#           start: npm run start-prod
#           wait-on: http://localhost:5000
#           wait-on-timeout: 240
