name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    if: ${{ github.event_name == 'push' && !contains( github.event.head_commit.message, '#skip') }}
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy app
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: New deployment.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Failed deployment
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
              severity: error
              details: Deployment failure.
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
