name: Periodic Health Check
on:
  schedule:
    - cron: '10 * * * *'

jobs:
  health-check-request:
    runs-on: ubuntu-20.04
    steps:
      - name: check url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://divine-sound-4603.fly.dev/health
          max-attempts: 3 # Optional, defaults to 1
          retry-all: false # Optional, defaults to "false"
