00 00 * * THU
name: Periodic Health Check

on:
  schedule:
    - cron: '00 00 * * THU'
  push: 
    branches:
      - master

jobs: 
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: ping
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://shrouded-peak-78795.herokuapp.com/health"
