name: Health Check

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://fullstack-2021-part11.herokuapp.com/health
          follow-redirect: no
          max-attempts: 3
          retry-delay: 15s
          retry-all: no
