on:
  schedule:
    - cron: "30 0 * * *"
jobs:
  Perodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Check the following url
          url: https://full-stack-open-pokedex-ariful-694d15d9d278.herokuapp.com/health
          max-attempts: 3
          retry-delay: 45s
