name: Hello-World

on:
  push:
    branches:
      - master

jobs:
  hello_world_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"

      - name: Now it is
        run: "date"

      - name: Directory Content
        run: "ls -l"
