name: Hello world!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print date
        run: |
          date
      -name: Print ls
        run: |
          ls
