name: Hello World!

on:
  push:
    branches: -master

jobs:
    hello_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Say Hello
            run: |
                echo "Hello World"