name: Hello!

on:
        push:
                branches:
                - master

jobs:
        hello_job:
                runs-on: ubuntu-18.04
                steps:
                - name: Say hello
                  run: |
                        echo "Hello CI!"