name: Hello World!

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [open,synchronize]
jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello world!"
  now_it_is:
    runs-on: ubuntu-18.04
    steps:
      - name: Now it is
        run: |
          date
  directory_content:
    runs-on: ubuntu-18.04
    steps:
      - name: Directory content
        run: |
          ls -l