name: Hello World! and heres the date

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello and date
        run: |
          echo "Hello World!"
          date
      - name: Folder contents
        run: |
          echo ls