name: Hello world!

on:
    push:
        branches:
            - master

jobs:
    hello_world_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Say Hello
              run: |
                echo "Hello Gihub Actions"
            - name: Now it is
              run: |
                echo "`Date`"
            - name: Directory Content
              run: |
                echo `ls -l`