name: Hello

on: push
jobs:
  hello-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: time
        run: date
      - name: directory content
        run: ls -l
