name: Periodic health check

on:
  schedule:
    - cron: '10,20,40 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: check the deployed url
      uses: jtalk/url-health-check-action@v3
      with:
        url: 'https://fspokedex.fly.dev/health'
        follow-redirect: false
        max-attempts: 3
        retry-delay: 10s
        retry-all: false
    - name: failed
      if: ${{ failure() }}
      run: echo "Health check failed!"

    - name: succeeded
      if: ${{ success() }}
      run: echo "Healtch check success"
