name: Periodic Health Check!

on: 
  schedule:
    - cron:  '* * 13 * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v1.5
        with:
          url: "https://natasharp-pokedex.herokuapp.com"