name: scheduled healtCheck

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduledHealtCheck:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: "https://mypokedex3456.herokuapp.com/health"
        follow-redirect: no 
        max-attempts: 3  
        retry-delay: 5s 
      
 

