name: Ping

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-18.04
    steps: 
      - name: ping
        uses: Jtalk/url-health-check-action@v1.3
        with:
          url: pirhon-pokedex.herokuapp.com/health
          max-attempts: 1 
