name: Periodic Health Check

on:
  schedule:
    - cron: '0 * * * *' # Schedule the workflow to run every 24 hours

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: 
        run : echo "This step will run on every one minute"
      - name: Perform Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: 'https://full-stack-open-pokedex-7vtq.onrender.com'
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s