name: Scheduled Health Check

on:
  schedule:
    -cron: '*/15 * * * *' # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

jobs:
  URL_Health_Check:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@2ff10af730f912a7b51f4e3868d9cb30de170a6b
      with:
        # Check the following URLs one by one sequentially
        url: https://ndeamador-fso2020-pokedex.herokuapp.com/health
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: no # Optional, defaults to "no"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1